spring:
  main:
    allow-bean-definition-overriding: true
projects:
  member:
    hibernate:
      property:
        "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect
        "[hibernate.show_sql]": false
        "[hibernate.hbm2ddl.auto]": update
        "[hibernate.cache.use_second_level_cache]": false
        "[hibernate.cache.use_query_cache]": false
    datasource:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://${member-db-host}:${member-db-port}/${member-db-database}
        username: ${member-db-user}
        password: ${member-db-passwd}

  auction:
    hibernate:
      property:
        "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect
        "[hibernate.show_sql]": false
        "[hibernate.hbm2ddl.auto]": update
        "[hibernate.cache.use_second_level_cache]": false
        "[hibernate.cache.use_query_cache]": false
    datasource:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://${auction-db-host}:${auction-db-port}/${auction-db-database}
        username: ${auction-db-user}
        password: ${auction-db-passwd}

  receipt:
    hibernate:
      property:
        "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect
        "[hibernate.show_sql]": false
        "[hibernate.hbm2ddl.auto]": update
        "[hibernate.cache.use_second_level_cache]": false
        "[hibernate.cache.use_query_cache]": false
    datasource:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://${receipt-db-host}:${receipt-db-port}/${receipt-db-database}
        username: ${receipt-db-user}
        password: ${receipt-db-passwd}
